### ISSUE TITLE
ImportError: No module named oauth2client.client

### ISSUE THREAD

**Issue by bilics** [andygeers/firebase-keysafe#1]
Hi,

I just followed the instructions but I am getting the error: 

ImportError: No module named oauth2client.client

I have already tried suggestions from SO posts like:

https://stackoverflow.com/questions/44011776/how-to-prevent-importerror-no-module-named-oauth2client-client-on-google-app

but no luck...

Can you share exactly what versions of packages (and python) are you using ?

Thanks!

**Comment by andygeers** [comment]
I believe this is resolved now by explicitly adding the package to requirements.txt
