### ISSUE TITLE
Where to store or fetch the KMS key on android side?

### ISSUE THREAD

**Issue by NainalChauhan** [andygeers/firebase-keysafe#6]
I have question regarding your blog post, whether we have store to the KMS key in client side to encrypt and decrypt the DEK or we will fetch this KMS key from server and perform the operation on client side.

**Comment by andygeers** [comment]
I'm not sure I fully understand the question... but KMS is a Google Cloud service, they hold the encryption key (KEK), and this service just talks to theirs to do the actual decrypting of the DEK. This service then returns the decrypted DEK to the client who is responsible for securely storing it and using it.

**Comment by NainalChauhan** [comment]
Thanks, So Google Cloud service will perform the encryption and decryption at their server and it will return the encrypted DEK to client.

**Comment by andygeers** [comment]
The encryption and decryption of the *DEK*, yes - they will then return the *decrypted* DEK to the client to do the actual encryption and decryption of the user data

**Comment by andygeers** [comment]
If you haven't already, it is essential to use this code in conjunction with the accompanying blog post: http://www.geero.net/2017/05/how-to-encrypt-a-google-firebase-realtime-database/
