### ISSUE TITLE
Insecure (or at least very unusual) key generation

### ISSUE THREAD

**Issue by dmjones** [andygeers/firebase-keysafe#7]
Just having a dig around this project, after reading your interesting blog post.

I noticed this code in `main.py`:

```python
  def generate_random_key(self):
    password = b"<USE_A_SECURE_RANDOM_PASSWORD_HERE>"
    salt = os.urandom(16)
    iterations = 20000
    key_len = 16
    raw_key = hashlib.pbkdf2_hmac('sha1', password, salt, iterations, key_len)
    ascii_key = self.line_ending_stripper.sub("", base64.b64encode(raw_key).decode('ascii'))
    return ascii_key
```

PBKDF2 should be used when turning a **user-supplied** password into a key of a suitable length.

If you want to generate a random key, just use `os.urandom(16)` (or whatever length you need). It is more secure.

**Comment by andygeers** [comment]
Thank you for this. I'm sure you are quite right. Fixed in 84ed040b1827392c853fa4d1f70c3410d76f7eaf
